title: Cevi Züri 11
email: info@zh11.ch

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zh11.ch" # the base hostname & protocol for your site

include:
  - _template_assets
  - script/gallery

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      main-menu-priority: "99"
      footer-menu-priority: "99"
      layout: "page"
  - scope:
      path: "content/news"
    values:
      news-entry: true


imageoptim:
  svgo: false   # Disabling svgo because it throws some error
  jpegrecompress:
    allow_lossy: true
    quality: 3
  jpegoptim:
    allow_lossy: true
    max_quality: 75
