title: Cevi Züri 11
email: info@zh11.ch

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zh11.ch" # the base hostname & protocol for your site
backend: "https://backend.zh11.ch"

timezone: Europe/Zurich

ignore_gdrive_cache: true

include:
  - _template_assets
  - script/gallery/*

exclude:

  # folders to ignore
  - backend # this folder contains the source code for the backend
  - fonts # only used during building
  - .idea # used by IDA
  - gallery
  - google_drive_cache

  # Docker files
  - docker-entrypoint.sh
  - docker-compose.yml
  - Dockerfile

  # other ignored files
  - README.md

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      main-menu-priority: "99"
      footer-menu-priority: "99"
      layout: "page"
  - scope:
      path: "content/news"
    values:
      news-entry: true

imageoptim:
  svgo: false   # Disabling svgo because it throws some error
  jpegrecompress:
    allow_lossy: true
    quality: 3
  jpegoptim:
    allow_lossy: true
    max_quality: 75
