# Only contains configs for development environment
# Override the default configs in _config.yml

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
backend: "http://localhost:5000"
