name: Jekyll Deploy Page

on:
  push:
    branches: [ master ]

jobs:
  jekyll_preview:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Retrieve the secret and decode it to a file
        env:
            API_KEY: ${{ secrets.API_KEY }}
        run: |
            echo $API_KEY > ./_secrets/credentials.json

      # Build the jekyll page
      - name: Build 🏗️
        uses: helaili/jekyll-action@v2
        with:
          build_only: true
          pre_build_commands: apk --update add imagemagick imagemagick-dev imagemagick-libs ttf-ubuntu-font-family

      - name: Deploy 🚀 to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: preview.zh11.ch