name: Jekyll Deploy Page

on:
  push:
    branches: [ master ]

jobs:
  jekyll_preview:
    name: Build and deploy Jekyll site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Build the Docker image # push The image to the docker hub
        run: docker build -t jeykell-custom-builder .

      - name: Retrieve the secret and decode it to a file
        env:
            API_KEY: ${{ secrets.API_KEY }}
        run: |
            echo $API_KEY > ./_secrets/credentials.json

      - name: Give folder access
        run: chmod 777 $PWD

      # Build the jekyll page
      - name: Build 🏗️
        run: docker run --rm --volume="$PWD:/srv/jekyll" jeykell-custom-builder  jekyll build

      - name: Deploy 🚀 to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: preview.zh11.ch